sigstore/k8s-manifest-sigstore

- CODEOWNERS
- CODE_OF_CONDUCT.md
- CONTRIBUTORS.md
- COPYRIGHT.txt
- README.md
Signed-off-by: Luke Hinds <lhinds@redhat.com>
> Project bootstrap

- .github/workflows/codeql-analysis.yml
Signed-off-by: Luke Hinds <lhinds@redhat.com>
> CodeQL action

- cmd/kubectl-sigstore/apply_after_verify.go
- cmd/kubectl-sigstore/sign.go
- cmd/kubectl-sigstore/verify.go
- cmd/kubectl-sigstore/verify_resource.go
- pkg/cosign/sign.go
- pkg/cosign/verify.go
- pkg/k8smanifest/option.go
- pkg/k8smanifest/resources/known-changes.yaml
- pkg/k8smanifest/sign.go
- pkg/k8smanifest/verify.go
- pkg/k8smanifest/verify_manifest.go
- pkg/k8smanifest/verify_resource.go
- pkg/util/image.go
- pkg/util/yaml.go
refactoring and bug fixes for the issue: https://github.com/sigstore/k8s-manifest-sigstore/issues/7
> refactor codes for extensibility and verification bug fixes 

- pkg/cosign/verify.go
- pkg/k8smanifest/verify.go
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
This PR aims to fix #11.
> fix for using public key, if public key used disable tlog

- README.md
Signed-off-by: Dan Lorenc <dlorenc@google.com>
> Fix a few typos in the README.

- cmd/kubectl-sigstore/sign.go
- pkg/cosign/sign.go
- pkg/k8smanifest/option.go
- pkg/k8smanifest/sign.go
- pkg/k8smanifest/verify.go
- pkg/util/file.go
This PR aims to add support for the signing and verifying process with annotations.
Notes for the reviewer:
- We have one breaking change in this PR, we change the flag `annotation` to `annotation-metadata`.
> image annotations added for signing/verifying process

- pkg/util/image.go
The command below will create a manifest image which contains a raw (non-compressed) YAML manifest unlike `kubectl sigstore sign` command.
```
$ cosign upload blob -f manifest.yaml <image>
```
This PR enables to load a raw YAML manifest.
> support a YAML manifest image created by `cosign upload blob` command

- .github/workflows/tests.yaml
- .golangci.yml
- Makefile
- go.mod
- go.sum
- pkg/util/sigtypes/pgp/pgp.go
- add `Tests` github action to do the following actions
- lint
- unit-test
- e2e-test
- update a dependency that was causing a lint error
> add github action for tests and lint

- go.mod
- go.sum
- pkg/util/manifestbuild/kustomize/provenance.go
Switches from using `github.com/in-toto/in-toto-golang/pkg/ssl` to `github.com/secure-systems-lab/go-securesystemslib/dsse`.
N/A.
See: https://github.com/in-toto/in-toto-golang/pull/122
```release-note
Uses new provider for DSSE.
```
> Switch DSSE provider to go-securesystemslib

- go.mod
- pkg/cosign/sign.go
- pkg/cosign/verify.go
- pkg/util/exec.go
- pkg/util/util_test.go
- fix [issue #53](https://github.com/sigstore/k8s-manifest-sigstore/issues/53) by calling cosign functions directly instead of util.SilentExecFunc()
- get tlog entry using the returned signature from SignBlobCmd() if needed
- remove util.SilentExecFunc() which is not used anymore
> fix blob signing issue on wsl2

- pkg/util/sigtypes/pgp/pgp.go
- pkg/util/sigtypes/sigtypes.go
- fix a issue around reading armored gpg public key
- improve error message when the signature type was not decided from public key
> fix armored gpg public key issue

- pkg/k8smanifest/verify_resource.go
- pkg/util/mapnode/diff.go
- pkg/util/mapnode/node.go
- fix how to report the diff results.
- With this PR, an attribute in the YAML manifest is reported as "before" and the one in the resource is "after".
- extend mapnode to support value pattern filter, which is not just a key name filter
- diff pattern such as below can be used for ignoring diff results.
```
key: "metadata.namespace"
values:
before: null
```
- enable direct manifest match with the namespace pattern check above
- handle "omitempty" conversion as non-difference in mapnode by default
> extend mapnode to enable efficient manifest matching

- cmd/kubectl-sigstore/cli/root.go
- docs/LATEST_RELEASE.md
- pkg/k8smanifest/verify_resource.go
- pkg/util/manifestbuild/kustomize/kustomize.go
> fix typos in codes and a doc

- pkg/k8smanifest/option.go
- pkg/k8smanifest/testdata/sample-deployment-signed-deployed.yaml
- pkg/k8smanifest/verify_resource.go
- pkg/k8smanifest/verify_test.go
- add `DisableDryRun` option to VerifyResourceOption
- add a test case with the option
> add DisableDryRun option for VerifyResource

- pkg/k8smanifest/verify_resource.go
- allow image changes for canonicalization such as adding `docker.io/` or `:latest`
> allow image change patterns by default

- docs/LATEST_RELEASE.md
- update the release doc for releasing v0.4.2
> prep for releasing v0.4.2

- README.md
- update README to mention Kyverno integration
> update README to mention Kyverno integration

- .github/workflows/cross.yaml
Related to:
- https://github.com/sigstore/k8s-manifest-sigstore/issues/123
Let's build a binary for Apple Silicon also, i.e:
- `kubectl-sigstore-darwin-arm64`
Using the new `macos-14` runners (now free for open source), which run on Apple Silicon, as per:
- https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
Binary for Apple Silicon (`darwin-arm64`)
> Binaries for `darwin-arm64` (Apple Silicon)

- pkg/util/image.go
- fix tar path issue with parent directory
> fix tar path issue with parent directory

- .github/workflows/codeql-analysis.yml
- .github/workflows/tests.yaml
- update CodeQL GitHub action to v2
> update CodeQL GitHub action to v2
