cmd/kubectl-sigstore/verify_resource.go, pkg/k8smanifest/sign.go, pkg/k8smanifest/verify.go, pkg/k8smanifest/verify_resource.go, pkg/util/cache.go
this PR is for the issue: https://github.com/sigstore/k8s-manifest-sigstore/issues/8
- add `output` option to verify-resource command and enable to output verify-resource result in JSON/YAML format
- minimize the number of image pulls using on memory cache only in verify-resource
=> enable to output `verify-resource` result in JSON/YAML format

go.mod, pkg/cosign/sign.go
- add oidc options as default value to support cosign v1.0.1 keyless signing
=> fix `sign` command to set oidc option

go.mod
- update `require` in go.mod for avoiding too old versions
=> update cosign `require` version in go.mod 

pkg/k8smanifest/option.go, pkg/k8smanifest/verify_resource.go
add an option `DryRunNamespace` to `VerifyResourceOption` , and this option decides which namespace is used for dryrun inside `verify-resource` instead of `default` namespace .
=> add an option to configure a namespace for dryrun in `verify-resource`

pkg/k8smanifest/verify.go
fix a bug around verification configuration for annotation-embedded signature
=> fix manifest detection config bug

cmd/kubectl-sigstore/sign.go, pkg/util/file.go
- fix issue of relative path input like "../xxxx" for sign command
- fix issue of output file path like "./xxxx/.signed" against directory path input for sign command
=> fix input path issue in sign command

cmd/kubectl-sigstore/verify_resource.go, pkg/k8smanifest/option.go, pkg/util/gzip.go, pkg/util/kubeutil/kubeutil.go
enable the command like this as equivalent to a local config file
```
$ kubectl sigstore verify-resource cm -n sample-ns sample-cm --config-type constraint --config-name sample-constraint
$ kubectl sigstore verify-resource cm -n sample-ns sample-cm --config config.yaml
```
=> enable to load config from constraint resource in a cluster

cmd/kubectl-sigstore/main.go, cmd/kubectl-sigstore/manifest_build.go, go.mod, pkg/util/manifestbuild/kustomize/kustomize.go, pkg/util/manifestbuild/kustomize/provenance.go
This PR aims to add `manifest-build` command to generate a YAML manifest with its provenance.
Based on the issue https://github.com/sigstore/k8s-manifest-sigstore/issues/25
=> add `manifest-build` command for YAML manifest provenance

cmd/kubectl-sigstore/verify_resource.go, pkg/k8smanifest/provenance.go, pkg/k8smanifest/verify.go, pkg/util/cache.go, pkg/util/file.go, pkg/util/util.go
- enable local file cache for further speed up after enabling concurrency
- use *K8S_MANIFEST_LOCAL_FILE_CACHE=1* env variable for the flag of this feature
- refactor cache initialization
=> enable local file cache for verify-resource speed up

cmd/kubectl-sigstore/verify_resource.go, go.mod, pkg/k8smanifest/verify_resource.go, pkg/util/cache.go
- split verify-resource command steps into 2 major steps, `initialize` and `verify-resource`
- apply concurrent execution to both of these 2 steps so that it could reduce the time to complete the command
- add a few log outputs to verify-resource command
=> improve verify-resource speed with concurrency in go

Makefile, cmd/kubectl-sigstore/main.go, cmd/kubectl-sigstore/version.go, example/admission-controller/config/common/configmap.yaml, example/config.yaml, pkg/util/version.go
- add `version` command which can show consistent results with `cosign version` / `kubectl version`
Example
```
$ kubectl sigstore version
{"Major":"","Minor":"","GitVersion":"develop","GitCommit":"6a68624364450d015ee1abc75fb5647a8d7b18d4","GitTreeState":"dirty","BuildDate":"2021-09-07T06:49:43Z","GoVersion":"go1.16.2","Compiler":"gc","Platform":"darwin/amd64"}
$ kubectl sigstore version
{"Major":"0","Minor":"1","GitVersion":"v0.1.0","GitCommit":"6a68624364450d015ee1abc75fb5647a8d7b18d4","GitTreeState":"dirty","BuildDate":"2021-09-07T06:49:43Z","GoVersion":"go1.16.2","Compiler":"gc","Platform":"darwin/amd64"}
```
=> enable `version` command to show version of the executable

pkg/util/image.go
- an issue for signing a directory has been fixed
=> fix issue of signing a directory

cmd/kubectl-sigstore/cli/sign.go, cmd/kubectl-sigstore/cli/sign_test.go, cmd/kubectl-sigstore/cli/testdata/sample-configmap-concat.yaml, pkg/k8smanifest/sign.go, pkg/util/file.go
- fix image annotation option handling
- support concatenated YAML manifest when image annotation enabled
- add test case for signing concatenated YAML
- fix tar gz decompress util function
=> fix issue in signing for concatenated YAML manifests

pkg/cosign/sign.go, test/e2e/e2e_test.go, test/e2e/testdata/sample-configmap-exp.yaml
- fix keyed verification issue which was caused by trying to get a signer name from public key in tlog instead of certificate.
- add test cases for keyed & experimental-enabled signing and verification.
=> fix keyed verification issue when experimental enabled

pkg/util/sigtypes/sigtypes.go
- support all cosign keyRef types (e.g. `k8s://namespace/secretname` for a public key in a kubernetes secret).
=> support all cosign keyRef types

cmd/kubectl-sigstore/cli/sign.go, cmd/kubectl-sigstore/cli/verify_resource.go, pkg/k8smanifest/option.go, pkg/k8smanifest/provenance.go, pkg/k8smanifest/sign.go, pkg/k8smanifest/verify.go, pkg/util/kubeutil/kubeutil.go, pkg/util/sigtypes/pgp/pgp.go, pkg/util/sigtypes/sigtypes.go, pkg/util/sigtypes/x509/x509.go
- support public key seceret in a k8s cluster for all signature types including gpg and x509. it will be able to specify the secret with `k8s://namespace/secretname`
=> support public key in a kubernetes secret for all signature types

pkg/k8smanifest/option.go, pkg/k8smanifest/testdata/sample-configmap-signed-mutating-1.yaml, pkg/k8smanifest/testdata/sample-configmap-signed-mutating-2.yaml, pkg/k8smanifest/verify_resource.go, pkg/k8smanifest/verify_test.go
- add `inclusionMatch` function for supporting verification in mutating admission controller
- users can enable this verification by calling `VerifyResource()` with an option `VerifyMutatingResource = true`
=> support verification for multiple mutating webhooks

README.md, cmd/kubectl-sigstore/cli/apply_after_verify.go, cmd/kubectl-sigstore/cli/verify.go, cmd/kubectl-sigstore/cli/verify_resource.go, pkg/util/file.go, pkg/util/sigtypes/pgp/pgp.go, pkg/util/sigtypes/x509/x509.go, test/e2e/e2e_test.go
- support public key from environment variable which starts with `env://`. this is the same way as cosign.
- add a test case with public key from env var
- update help texts that are shown when `--help` option is used
=> support public key from environment variable as cosign does

docs/LATEST_RELEASE.md, pkg/k8smanifest/option.go, pkg/k8smanifest/sign.go, pkg/k8smanifest/testdata/sample-configmap-multi-signed.yaml, pkg/k8smanifest/verify.go, pkg/k8smanifest/verify_manifest.go, pkg/k8smanifest/verify_resource.go, pkg/k8smanifest/verify_test.go
- support multiple signatures by using AnnotationConfig
- add a test case for multiple signature verification
- update AnnotationConfig to make the annotation name configurable  (e.g. use `msg` instead of `message`)
- update release note
=> support multiple signatures for verification

cmd/kubectl-sigstore/cli/sign.go, cmd/kubectl-sigstore/cli/sign_test.go, pkg/k8smanifest/option.go, pkg/k8smanifest/sign.go, pkg/k8smanifest/sign_test.go, pkg/util/yaml.go
- The current signing method creates a tarball from the input YAML manifest / the input directory for signing, but this causes non-reproducible message serialization and it makes `message` annotation in the signed manifest difficult to check.
- Instead, we add a new signing method which directly signs the raw YAML manifest (or raw manifests in the directory) and it is enabled by `--tarball=no` option with this PR.
- We make the current method deprecated in the next release (v0.3.1) and it will be unavailable in v0.5.0. Once it becomes unavailable, the new signing method will be the default one.
=> make the current signing method with tarball deprecated

README.md, cmd/kubectl-sigstore/cli/apply_after_verify.go, cmd/kubectl-sigstore/cli/manifest_build.go, cmd/kubectl-sigstore/cli/sign.go, cmd/kubectl-sigstore/cli/sign_test.go, cmd/kubectl-sigstore/cli/verify.go, cmd/kubectl-sigstore/cli/verify_resource.go, example/admission-controller/main.go, example/admission-controller/pkg/config/config.go, go.mod, go.sum, pkg/cosign/sign.go, pkg/cosign/verify.go, pkg/k8smanifest/opiton_test.go, pkg/k8smanifest/option.go, pkg/k8smanifest/provenance.go, pkg/k8smanifest/resources/default-config.yaml, pkg/k8smanifest/sign.go, pkg/k8smanifest/sign_test.go, pkg/k8smanifest/testdata/sample-configmap-multi-signed.yaml, pkg/k8smanifest/verify.go, pkg/k8smanifest/verify_manifest.go, pkg/k8smanifest/verify_resource.go, pkg/k8smanifest/verify_test.go, pkg/util/file.go, pkg/util/image.go, pkg/util/kubeutil/kubeutil.go, pkg/util/manifestbuild/kustomize/provenance.go, pkg/util/yaml.go
- users can sign their YAML manifest with `--append-signature` (or `-A`) option. This allows the signed manifest to store multiple signatures in the annotation without removing the pre-existing signatures. `signature_1`, `signature_2` ... will be automatically added if the option is enabled while signing.
- users can verify their YAML manifest / Kubernetes resource that have multiple signatures in the annotation.
- fix an issue of making message data so that consistent message data can be used when the same file is signed multiple times.
- add test cases
=> support multiple signatures both for signing and verification

pkg/cosign/sign.go
- add workaround for a bug in `GetTlogEntry()` function in cosign
- set keyless default timeout to the default value of cosign
=> fix keyless signing issue that tlog entry cannot be got after signing

cmd/kubectl-sigstore/cli/apply_after_verify.go, cmd/kubectl-sigstore/cli/sign.go, cmd/kubectl-sigstore/cli/sign_test.go, cmd/kubectl-sigstore/cli/verify.go, cmd/kubectl-sigstore/cli/verify_resource.go, cmd/kubectl-sigstore/cli/verify_resource_test.go, pkg/cosign/sign.go, pkg/cosign/sign_test.go, pkg/cosign/verify.go, pkg/cosign/verify_test.go, pkg/k8smanifest/option.go, pkg/k8smanifest/sign.go, pkg/k8smanifest/verify.go, pkg/k8smanifest/verify_manifest.go, pkg/k8smanifest/verify_resource.go, pkg/util/sigtypes/x509/x509.go
- `--rekor-url` option is added both for sign and verify command. (still environment variable `REKOR_SERVER` can be used.)
- `--certificate` and `--certificate-chain` are supported as same as cosign verify command.
- `--oidc-issuer` is supported for specifying fulcio OIDC issuer.
=> add sign & verify options to support cosign command options

pkg/k8smanifest/errors.go, pkg/k8smanifest/verify.go, pkg/k8smanifest/verify_resource.go, pkg/k8smanifest/verify_test.go
- add the following 3 error definitions as structs so that developers can handle the returned errors from `VerifyResource()`
- MessageNotFoundError
- SignatureNotFoundError
- SignatureVerificationError
- add utility functions to detect the error type
- enable inclusionMatch without dryrun
=> add some special error definitions and handling

cmd/kubectl-sigstore/cli/sign.go, cmd/kubectl-sigstore/cli/sign_test.go, cmd/kubectl-sigstore/cli/verify.go, cmd/kubectl-sigstore/cli/verify_resource.go, cmd/kubectl-sigstore/cli/verify_resource_test.go, docs/LATEST_RELEASE.md, go.mod, pkg/cosign/sign.go, pkg/cosign/sign_test.go, pkg/cosign/verify.go, pkg/k8smanifest/option.go, pkg/k8smanifest/provenance.go, pkg/k8smanifest/sign.go, pkg/k8smanifest/verify.go, pkg/k8smanifest/verify_manifest.go, pkg/k8smanifest/verify_resource.go, pkg/util/image.go
The main update in v0.4.1 release is updating cosign version to v1.12.1.
- add 2 CLI options that have been added by cosign v1.12.1.
- update release note doc
=> bump cosign to v1.12.1 for releasing v0.4.1

.github/scorecard.yml
The motivation for this PR is to make k8s-manifest-sigstore be warned about supply-chain security issues using Scorecard tool.
The PR adds Scorecard workflow using [sigstore/community reusable workflow](https://github.com/sigstore/community/blob/main/.github/workflows/reusable-scorecard.yml).
The PR does not add Scorecard badge to README, let me know if you would like that.
Config changes: Add Scorecard to warn about k8s-manifest-sigstore possible security issues
None.
=> Add scorecard analysis tool

.github/workflows/slsa-goreleaser.yml, .slsa-goreleaser-darwin-arm64.yml
- add SLSA goreleaser config for darwin-arm64
=> add SLSA goreleaser config for darwin-arm64

.github/scorecard.yml
The reusable workflow in community gets regular updates from dependabot. We don't cut releases for community, so if you don't run the reusable workflow off main, you'll be stuck on an outdated version of the underlying scorecard action.
=> Run reusable scorecard workflow at main

.github/workflows/cross.yaml
- update version of `upload` github action because the version previously used was deprecated
=> update version of `upload` github action
